<a href="https://colab.research.google.com/github/diyasingla1104/ML-lab/blob/main/ml_8pca_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Given data
X = np.array([[4, 11], [8, 4], [13, 5], [7, 14]])

# Step 1: Compute the mean
mean_X = np.mean(X, axis=0)
print("Mean of each feature:\n", mean_X)

# Step 2: Compute the covariance matrix
cov_matrix = np.cov(X.T)
print("Covariance Matrix:\n", cov_matrix)

# Step 3: Compute eigenvalues and eigenvectors
eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)
print("Eigenvalues:\n", eigen_values)
print("Eigenvectors:\n", eigen_vectors)

# Step 4: Sort eigenvalues and eigenvectors in descending order
sorted_indices = np.argsort(eigen_values)[::-1]
eigen_values = eigen_values[sorted_indices]
eigen_vectors = eigen_vectors[:, sorted_indices]

print("Sorted Eigenvalues:\n", eigen_values)
print("Sorted Eigenvectors:\n", eigen_vectors)

# Step 5: Select principal components
principal_components = eigen_vectors[:, :2]
print("Principal Components:\n", principal_components)




Mean of each feature:
 [8.  8.5]
Covariance Matrix:
 [[ 14. -11.]
 [-11.  23.]]
Eigenvalues:
 [ 6.61513568 30.38486432]
Eigenvectors:
 [[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]
Sorted Eigenvalues:
 [30.38486432  6.61513568]
Sorted Eigenvectors:
 [[ 0.55738997 -0.83025082]
 [-0.83025082 -0.55738997]]
Principal Components:
 [[ 0.55738997 -0.83025082]
 [-0.83025082 -0.55738997]]
